language: generic
sudo: required
service:
    - docker

before_install:
    - docker build -t svvpro/multi-docker -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true svvpro/multi-docker npm run test

after_success:
    - docker build -t svvone/multi-client ./client
    - docker build -t svvone/multi-nginx ./nginx
    - docker build -t svvone/multi-server ./server
    - docker build -t svvone/multi-worker ./worker
    #Log in to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker  login -u "$DOCKER_USERNAME" --password-stdin
    #Take those images and push them to docker hub
    - docker push svvone/multi-client
    - docker push svvone/multi-nginx
    - docker push svvone/multi-server
    - docker push svvone/multi-worker
deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-central-1
    app: multi-docker  
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-central-1-343766802350
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
